#!/bin/bash
#SBATCH --job-name=coverage # Job name
#SBATCH -e coverage_error
#SBATCH --mail-type=ALL # Mail events (BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=email # Where to send mail
#SBATCH --ntasks=1 # Run a single task
#SBATCH --cpus-per-task=20 # Number of CPU cores per task
#SBATCH --mem=20gb
#SBATCH --nodes=1
#SBATCH --time=24:00:00 # Time limit hrs:min:sec
#SBATCH --output=overage.log # Standard output/error
############################################
module load samtools
#Calculate coverage stats 
for BAM in *nuDNA_aligned_sorted_unique.bam
do
  # calculate mean and standard deviation of bam coverage
  STATS=$(samtools depth -a $BAM | awk '{sum+=$3; sumsq+=$3*$3} END { print sum/NR,"\t", sqrt(sumsq/NR - (sum/NR)**2)}')
  echo -e "${BAM}\t${STATS}"
done >> nuDNA_aligned_sorted_unique_coverage.txt
