#!/bin/bash
#SBATCH --job-name=fastqc_raw # Job name
#SBATCH -e fastqc_raw.error
#SBATCH --mail-type=ALL # Mail events (BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=morgan@bio.ku.dk # Where to send mail
#SBATCH --ntasks=1 # Run a single task
#SBATCH --cpus-per-task=10 # Number of CPU cores per task
#SBATCH --mem=2gb
#SBATCH --nodes=1
#SBATCH --time=5:00:00 # Time limit hrs:min:sec
#SBATCH --output=fastqc_raw.log # Standard output/error
############################################
module load openjdk perl fastqc
for file in *fastq.gz
do 
fastqc ${file} 
done 
