#!/bin/bash
#SBATCH --job-name=repeat.mask # Job name
#SBATCH -e repeat.mask.error
#SBATCH --mail-type=ALL # Mail events (BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=email # Where to send mail
#SBATCH --ntasks=1 # Run a single task
#SBATCH --cpus-per-task=15 # Number of CPU cores per task
#SBATCH --mem=10gb
#SBATCH --nodes=1
#SBATCH --time=24:00:00 # Time limit hrs:min:sec
#SBATCH --output=repeat.mask.log # Standard output/error
############################################
module load samtools
module load bedtools

for BAM in *.bam
do

INDIR=final.nuclear.bams

###########
OUTDIR=${INDIR}

BED=GCA_025265405.1_mMesDen1_rm.bed
shortid=`echo $BAM | cut -f1 -d "_"`

##########################################################################################

bedtools intersect -abam ${INDIR}/${BAM} -b ${BED} -v > ${OUTDIR}/${shortid}_dedup_noRepeats.bam 2>${OUTDIR}/${shortid}_RM_log.txt

samtools index ${OUTDIR}/${shortid}_dedup_noRepeats.bam

done
