#!/bin/bash
#SBATCH -J IBS_genome_wide_2024     ## you can give whatever name you want here to identify your job
#SBATCH -o IBS_genome_wide_2024.log.out ## name a file to save log of your job
#SBATCH -e IBS_genome_wide_2024.error       ## save error message if any
#SBATCH --mail-user=morgan@bio.ku.dk  ## your email account to receive notification of job status
#SBATCH --mail-type=ALL 
#SBATCH -t 16:00:00    
#SBATCH --ntasks=1                   # Run a single task
#SBATCH --cpus-per-task=8            # Number of CPU cores per task
#SBATCH --mem=50gb
############################################
module load miniconda
conda activate /projects/mjolnir1/apps/conda/angsd-0.921

#A total of 9 species/files in the bam list
bams=bam.list
chrms=autosomes.GCA_025265405.1_mMesDen1_primary_haplotype_genomic.txt

#1Mb windows
angsd -bam ${bams} -out genome_wide/genome_wide -rf ${chrms} -doCounts 1 -P 8 -makeMatrix 1 -doIBS 2 -minInd 9 -minMapQ 30 -minQ 30 -uniqueOnly 1 -remove_bads 1 -setMinDepthInd 10
